name: 24/7 ATOK Reward Bot

on:
  workflow_dispatch:  # ম্যানুয়ালি রান করার জন্য
  schedule:
    - cron: "0 */5 * * *"  # প্রতি ৫ ঘণ্টা পরপর অটো রান হবে (গিটহাবের লিমিট বাইপাস করতে)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: |
          pip install requests urllib3

      - name: Run ATOK Bot
        run: python bot.py
